In [19]:
%load_ext autoreload
%autoreload 2
%config IPCompleter.greedy=True

from proteinworkshop.datasets.base import SequenceDataset

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [23]:
seq_dataset = SequenceDataset(fasta_file='test.fasta')

In [25]:
seq_dataset.embed()

[05/08/23 14:27:14] INFO     Creating ESM embeddings for 4 sequences in                                 ]8;id=387952;file:///rds/user/ked48/hpc-work/protein_workshop/src/datasets/base.py\base.py]8;;\:]8;id=696627;file:///rds/user/ked48/hpc-work/protein_workshop/src/datasets/base.py#332\332]8;;\
                             /rds/user/ked48/hpc-work/protein_workshop/notebooks/embeddings                        

In [24]:
seq_dataset.sequences

[('PETase',
  'MGSSHHHHHHSSGLVPRGSHMRGPNPTAASLEASAGPFTVRSFTVSRPSGYGAGTVYYPTNAGGTVGAIAIVPGYTARQSSIKWWGPRLASHGFVVITIDTNSTLDQPSSRSSQQMAALRQVASLNGTSSSPIYGKVDTARMGVMGWSMGGGGSLISAANNPSLKAAAPQAPWDSSTNFSSVTVPTLIFACENDSIAPVNSSALPIYDSMSRNAKQFLEINGGSHSCANSGNSNQALIGKKGVAWMKRFMDNDTRYSTFACENPNSTRVSDFRTANCSLEDPAANKARKEAELAAATAEQ'),
 ('1EZG Antifreeze protein',
  'QCTGGADCTSCTGACTGCGNCPNAVTCTNSQHCVKANTCTGSTDCNTAQTCTNSKDCFEANTCTDSTNCYKATACTNSSGCPGH'),
 ('Hallucinated protein HALC1_878',
  'MSGMKKLYEYTVTTLDEFLEKLKEFILNTSKDKIYKLTITNPKLIKDIGKAIAKAAEIADVDPKEIEEMIKAVEENELTKLVITIEQTDDKYVIKVELENEDGLVHSFEIYFKNKEEMEKFLELLEKLISKLSGS'),
 ('Neuraminidase',
  'VKLAGNSSLCPINGWAVYSKDNSIRIGSKGDVFVIREPFISCSHLECRTFFLTQGALLNDKHSNGTVKDRSPHRTLMSCPVGEAPSPYNSRFESVAWSASACHDGTSWLTIGISGPDNGAVAVLKYNGIITDTIKSWRNNILRTQESECACVNGSCFTVMTDGPSNGQASYKIFKMEKGKVVKSVELDAPNYHYEECSCYPNAGEITCVCRDNWHGSNRPWVSFNQNLEYQIGYICSGVFGDNPRPNDGTGSCGPVSSNGAYGVKGFSFKYGNGVWIGRTKSTNSRSGFEMIWDPNGWTETDSSFSVKQDIVAITDWSGYSGSFVQHPELTGLDCIRPCFWVELIRGRPKESTIWTSGSSI

In [26]:
embeddings = seq_dataset.embed(save=False)

[05/08/23 14:28:33] INFO     Creating ESM embeddings for 4 sequences in memory                          ]8;id=509472;file:///rds/user/ked48/hpc-work/protein_workshop/src/datasets/base.py\base.py]8;;\:]8;id=226845;file:///rds/user/ked48/hpc-work/protein_workshop/src/datasets/base.py#337\337]8;;\

In [27]:
embeddings

[tensor([-0.0313, -0.0534, -0.0485,  ..., -0.1103, -0.0181,  0.0504]),
 tensor([-0.0850,  0.0370, -0.1043,  ..., -0.0146,  0.0213,  0.0622]),
 tensor([ 0.1235, -0.0601, -0.0774,  ..., -0.0833, -0.1031, -0.0553]),
 tensor([ 0.0347,  0.0129, -0.0437,  ..., -0.1534, -0.0904,  0.1508])]

In [19]:
print(embeddings[0].shape)

torch.Size([1280])


In [28]:
#create SequenceDataset object with representative sequence
seqs = SequenceDataset(fasta_file='test.fasta', seq_representative="Neuraminidase")

In [29]:
seqs.seq_representative

('Neuraminidase',
 'VKLAGNSSLCPINGWAVYSKDNSIRIGSKGDVFVIREPFISCSHLECRTFFLTQGALLNDKHSNGTVKDRSPHRTLMSCPVGEAPSPYNSRFESVAWSASACHDGTSWLTIGISGPDNGAVAVLKYNGIITDTIKSWRNNILRTQESECACVNGSCFTVMTDGPSNGQASYKIFKMEKGKVVKSVELDAPNYHYEECSCYPNAGEITCVCRDNWHGSNRPWVSFNQNLEYQIGYICSGVFGDNPRPNDGTGSCGPVSSNGAYGVKGFSFKYGNGVWIGRTKSTNSRSGFEMIWDPNGWTETDSSFSVKQDIVAITDWSGYSGSFVQHPELTGLDCIRPCFWVELIRGRPKESTIWTSGSSISFCGVNSDTVGWSWPDGAELPFTIDK')